#!/bin/bash
# vim:fileencoding=utf-8:ts=2:sw=2:expandtab

pushd /opt/acn-linux

F="/etc/profile.d/acn-linux.sh"
echo "Install $F"
echo 'pathmunge /opt/acn-linux/bin' > $F

F="/etc/profile.d/acn-linux-vim.sh"
echo "Install $F"
echo 'alias vi=vim' > $F
echo 'export EDITOR=/usr/bin/vim'

F="/usr/lib64/python3.7/site-packages/acn-linux.pth"
echo "Install $F"
echo '/opt/acn-linux/python3.7' > $F


echo "--- Done! ---"
echo 

popd
