#!/usr/bin/python3
# vim:fileencoding=utf-8:ts=2:sw=2:expandtab

from binlib import *

user = 'root'

try:
  print()
  os.chdir(Path) #Important for git commands

  
  call(('git', 'fetch'))
    
  if GetInput_YesNo('Do you want to rebase "{0}" to the latest master? (DEF)? '.format(Path), Default='yes'):
    check_call(('git', 'rebase', 'origin/master'))


except Exception as e:
  print()
  print()
  print('*** Fatal Error ***')
  print(e)
  print()
except KeyboardInterrupt:
  print()  
  print()
  print('*** User Abort ***')
  print()

