#!/bin/bash
# chkconfig: 2345 20 80
# description: init.d script for headless openoffice.org (2.3+ for RHEL5 64bit)
#
# processname: openoffice
#
# source function library
. /etc/rc.d/init.d/functions

RETVAL=0
SOFFICE_PATH='/usr/lib64/libreoffice/program/soffice.bin'
SOFFICE_ARGS='--accept=socket,host=localhost,port=8100;urp;StarOffice.ServiceManager --headless --norestore --nofirststartwizard --nologo'
SOFFICE_PIDFILE=/var/run/soffice.bin.pid

start_soffice() {
       echo -n $"Starting headless OpenOffice"
       $SOFFICE_PATH $SOFFICE_ARGS >/dev/null 2>&1 &
       [ $? -eq 0 ] && echo_success || echo_failure
       pidof soffice.bin > $SOFFICE_PIDFILE
       echo
}
start() {
       start_soffice
}
stop() {
       echo -n $"Stopping headless OpenOffice"
       killproc soffice.bin
       echo
}
case "$1" in
       start)
	       start
	       ;;
       stop)
	       stop
	       ;;
       restart)
	       stop
	       start
	       ;;
       *)
	       echo $"Usage: $0 {start|stop|restart}"
esac
